// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kendall_tau
double kendall_tau(arma::vec x, arma::vec y);
RcppExport SEXP _mixcausal_kendall_tau(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau(x, y));
    return rcpp_result_gen;
END_RCPP
}
// ContinuousInC
double ContinuousInC(arma::vec x, arma::vec y);
RcppExport SEXP _mixcausal_ContinuousInC(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ContinuousInC(x, y));
    return rcpp_result_gen;
END_RCPP
}
// BinaryContiInC
double BinaryContiInC(arma::vec x, arma::vec y);
RcppExport SEXP _mixcausal_BinaryContiInC(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(BinaryContiInC(x, y));
    return rcpp_result_gen;
END_RCPP
}
// BinaryInC
double BinaryInC(arma::vec x, arma::vec y);
RcppExport SEXP _mixcausal_BinaryInC(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(BinaryInC(x, y));
    return rcpp_result_gen;
END_RCPP
}
// OrdinalOrdinal
double OrdinalOrdinal(arma::vec x, arma::vec y);
RcppExport SEXP _mixcausal_OrdinalOrdinal(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(OrdinalOrdinal(x, y));
    return rcpp_result_gen;
END_RCPP
}
// CategoricalCategorical
double CategoricalCategorical(arma::vec x, arma::vec y);
RcppExport SEXP _mixcausal_CategoricalCategorical(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(CategoricalCategorical(x, y));
    return rcpp_result_gen;
END_RCPP
}
// LGC_sigma_AllType
arma::mat LGC_sigma_AllType(arma::mat x, std::vector<std::string> label);
RcppExport SEXP _mixcausal_LGC_sigma_AllType(SEXP xSEXP, SEXP labelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type label(labelSEXP);
    rcpp_result_gen = Rcpp::wrap(LGC_sigma_AllType(x, label));
    return rcpp_result_gen;
END_RCPP
}
// LGC_sigma_BC
arma::mat LGC_sigma_BC(arma::mat x, std::vector<std::string> label);
RcppExport SEXP _mixcausal_LGC_sigma_BC(SEXP xSEXP, SEXP labelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type label(labelSEXP);
    rcpp_result_gen = Rcpp::wrap(LGC_sigma_BC(x, label));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mixcausal_kendall_tau", (DL_FUNC) &_mixcausal_kendall_tau, 2},
    {"_mixcausal_ContinuousInC", (DL_FUNC) &_mixcausal_ContinuousInC, 2},
    {"_mixcausal_BinaryContiInC", (DL_FUNC) &_mixcausal_BinaryContiInC, 2},
    {"_mixcausal_BinaryInC", (DL_FUNC) &_mixcausal_BinaryInC, 2},
    {"_mixcausal_OrdinalOrdinal", (DL_FUNC) &_mixcausal_OrdinalOrdinal, 2},
    {"_mixcausal_CategoricalCategorical", (DL_FUNC) &_mixcausal_CategoricalCategorical, 2},
    {"_mixcausal_LGC_sigma_AllType", (DL_FUNC) &_mixcausal_LGC_sigma_AllType, 2},
    {"_mixcausal_LGC_sigma_BC", (DL_FUNC) &_mixcausal_LGC_sigma_BC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mixcausal(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
