# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kendall_tau <- function(x, y) {
    .Call(`_mixcausal_kendall_tau`, x, y)
}

#' Compute the latent covariance matrix when data is all type
#'
#' @param x A single matrix
#' @param label A vector of labels
#' @export
LGC_sigma_AllType <- function(x, label) {
    .Call(`_mixcausal_LGC_sigma_AllType`, x, label)
}

#' Compute the latent covariance matrix when data is binary and continuous
#'
#' @param x A single matrix
#' @param label A vector of labels
#' @export
LGC_sigma_BC <- function(x, label) {
    .Call(`_mixcausal_LGC_sigma_BC`, x, label)
}

