# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the Kendall' tau rank correlation
#'
#' @param x A vector
#' @param y A vector
#' @export
kendall_tau <- function(x, y) {
    .Call(`_mixcausal_kendall_tau`, x, y)
}

#' Estimate the correlation for continuous data based on Kendall's rank cor
#'
#' @param x A vector of continuous variables
#' @param y A vector of continuous variables
#' @export
ContinuousInC <- function(x, y) {
    .Call(`_mixcausal_ContinuousInC`, x, y)
}

#' Estimate the correlation for binary and continuous data based on Kendall's rank cor
#'
#' @param x A vector of binary variables
#' @param y A vector of continuous variables
#' @export
BinaryContiInC <- function(x, y) {
    .Call(`_mixcausal_BinaryContiInC`, x, y)
}

#' Estimate the correlation for binary data based on Kendall's rank cor
#'
#' @param x A vector of binary variables
#' @param y A vector of binary variables
#' @export
BinaryInC <- function(x, y) {
    .Call(`_mixcausal_BinaryInC`, x, y)
}

#' Estimate the correlation for ordinal data based on Kendall's rank cor
#'
#' @param x A vector of ordinal variables
#' @param y A vector of ordinal variables
#' @export
OrdinalOrdinal <- function(x, y) {
    .Call(`_mixcausal_OrdinalOrdinal`, x, y)
}

#' Estimate the correlation for categorical data based on Kendall's rank cor
#'
#' @param x A vector of categorical variables
#' @param y A vector of categorical variables
#' @export
CategoricalCategorical <- function(x, y) {
    .Call(`_mixcausal_CategoricalCategorical`, x, y)
}

#' Compute the latent covariance matrix when data is all type
#'
#' @param x A single matrix
#' @param label A vector of labels
#' @export
LGC_sigma_AllType <- function(x, label) {
    .Call(`_mixcausal_LGC_sigma_AllType`, x, label)
}

#' Compute the latent covariance matrix when data is binary and continuous
#'
#' @param x A single matrix
#' @param label A vector of labels
#' @export
LGC_sigma_BC <- function(x, label) {
    .Call(`_mixcausal_LGC_sigma_BC`, x, label)
}

